### ISSUE TITLE
Failure to solve twisty-passages

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#262] opened 2015-05-21 21:51 UTC
In this game, we should "walk straight straight" 199 times.  We manage to do it 198 times, but then go wrong at the last step.

Logs look very similar to when we were getting confused at the end of some of the other puzzles.  We think the game is complete from turn 1, but think it's a complete loss.  As an extra twist, we think that the correct move at turn one causes completion at depth 2!  Having played, we realise that it isn't complete for 198 moves (correct).  We then follow the right path until the very last move.

**Comment by arr28** [comment] 2015-05-21 22:06
Worth debugging with learning disabled.  For some strange reason, we save the plan even when it doesn't win.  That shouldn't happen.  We should look at our final score (which is correctly reported as 0) and only save the history to disk as a plan if we scored full marks.

Actually, having written that, I think we also save the history to disk if we completed the root before the end of the first turn (in which case, we reason that even a non-100-scoring solution is the best possible).  In this case, a bug in completion is causing a 0-scoring complete root.

**Comment by arr28** [comment] 2015-05-22 14:29
duplicateStateSmall also fails intermittently because we end up with a complete root (nearly instantaneously) that we think is a complete 50.  But 100 can be scored.

**Comment by SteveDraper** [comment] 2015-05-23 20:23
duplicateStateSmall is not the same issue, but I will look into it.

**Comment by SteveDraper** [comment] 2015-05-24 01:06
Twisty passages now fixed without breaking anything else.

The following are failing for me from the base set:

duplicateStateSmall
wargame02
wargame03
knightsmove
KnightsTourLarge

I have tried these in a version of Sancho from a couple of months ago, and they fail there also.

duplicateStateSmall is definitely a problem as it's a small tree (totally searchable by brute force in a fraction of a second), yet somehow gives inconsistent results.  I will continue to investigate it.

The wargame variants I am not aware we have ever solved, so not too worried for now.

knightsmove appears to just be a regular sized knight's tour, with nothing obviously special.  I cannot find any problem with the way it attempts to play it, so unsure why it doesn't solve, but no reason to believe it ever did reliably

KnightsTourLarge fails to build a propnet.  I have noticed that previously though so it's not new (and confirmed with an older version).  The weird thing is that when we get it on Tiltyard it plays fine!  Inability to build the propnet is totally consistent whenever I try to run it locally however

**Comment by SteveDraper** [comment] 2015-05-24 15:35
duplicateStateSmall (and indeed that entire family of puzzles) are more complicated versions of twisty-passages, intended to thwart solution-by-transposition.

The particular problem with duplicateStateSmall was the shallow-greedy-rollout => complete logic was incorrect in games that are not fixed sum (which is all puzzles, but more generally it's the fixed-summedness that is the issue).  The reason is that terminality at an intermediate score (relative to the latched range that is believed to be possible, which in most games will always be [0,100]) doesn't trigger stack-popping to look for a better line.  That logic requires absolute win/loss, which boils down to fixed sum.

With that guard added we solve this fine (and also medium and large variants)

**Comment by SteveDraper** [comment] 2015-05-24 16:22
Marking the wargame variants and knightsmove as omitted from the junit tests.  The wargame variants I am fairly sure we have never been able to, solve.  knightsmove is erratic, but I think this is just due to its statespace size.  The only slight oddity is that KnightsTourLarge (which works for me now I have cleared my repo cache) seems reliably solvable (it's a 9X9 tour) whereas knightsmove does not (an 8X8 tour).  However, it's possible that odd board sizes significantly constrain the 'likely looking' moves and that the 9X9 really is easier than the 8X8, so not worrying about it for now.

**Comment by SteveDraper** [comment] 2015-05-24 19:29
Adding back the following to the unit tests, as recent fixes seem to have sorted them out also:

blocksWorldSerial
blocksWorldParallel
incredible

**Closed** 2015-05-24 19:42 UTC
Labels: bug, P2
