### ISSUE TITLE
Null ref exception on last move with a plan in HunterBig

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#286] opened 2015-06-05 20:48 UTC
Tried HunterBig with more generous time limits (50,20) and it found no solution during metagaming, but after about 15 turns or so it hit a 100 result and cached a plan.  It then null-ref'd on the very last move! (and scored 98)

**Comment by SteveDraper** [comment] 2015-06-05 20:51
Note - the exceptions were in MCTS search even though it had a cached plan.  This rings a bell - something similar been seen recently in some other context??

**Comment by arr28** [comment] 2015-06-05 21:04
See the final part of #284.

**Comment by arr28** [comment] 2015-06-06 20:27
Closed as duplicate of part 7 of #284 (now fixed).

**Closed by arr28** 2015-06-06 20:27 UTC
Labels: bug, P1
