### ISSUE TITLE
'Guess Two Thirds' (6 player)' kills Sancho completely (needs to be killed and restarted)

### ISSUE THREAD

**Issue by SteveDraper** [SanchoGGP/ggp-base#215] opened 2015-04-17 12:24 UTC
Reason is that the propnet is truly vast, and takes (would take if it could finish) many hours to produce.  The effect is to totally hang up the process.

**Comment by arr28** [comment] 2015-04-17 12:54
Closing as duplicate of #213.

**Closed by arr28** 2015-04-17 12:54 UTC
Labels: bug, P2, T3
